localdb:
  image: postgres:11.2
  ports:
    - '5432:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=monakairine
    - POSTGRES_PASSWORD=123123
    - POSTGRES_DB=database
testdb:
  image: postgres:11.2
  ports:
    - '5433:5432'
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=monakairine
    - POSTGRES_PASSWORD=123123
    - POSTGRES_DB=database_teste
